name: saba-build-actions
on: [push]
jobs:
  build-gcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      #安装windows sdk
      # - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      #   with:
      #     sdk-version: 19041
      #设置mingw
      # - name: Set up MinGW
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x64
      - name: Install dependencies
        run: |
          cmake -G "Visual Studio 14 2015 Win64" ^
          -D CMAKE_INSTALL_PREFIX=<Your Bullet Physics install directory> ^
          -D INSTALL_LIBS=ON ^
          -D USE_MSVC_RUNTIME_LIBRARY_DLL=On ^
          -D BUILD_CPU_DEMOS=Off ^
          -D BUILD_OPENGL3_DEMOS=Off ^
          -D BUILD_BULLET2_DEMOS=Off ^
          -D BUILD_UNIT_TESTS=Off ^
          ..
          cmake --build . --config Debug --target ALL_BUILD
          cmake --build . --config Debug --target INSTALL
          cmake --build . --config Release --target ALL_BUILD
          cmake --build . --config Release --target INSTALL
          #sudo apt install -y cmake libbullet-dev libglu1-mesa-dev libx11-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev
          #sudo apt install -y mingw-w64 mingw-w64-i686-dev 
      - name: build
      #-DCMAKE_SYSTEM_VERSION=10.0.19041.0
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 14 2015 Win64" ^ -D SABA_BULLET_ROOT=<Your Bullet Physics install directory> ^-D SABA_GLFW_ROOT=glfw-3.3.6.bin.WIN64 ^
          ls

  # build-clang:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: |
  #         sudo apt update
  #         sudo apt install -y cmake libbullet-dev libglu1-mesa-dev libx11-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev
  #     - name: build
  #       env:
  #         C_COMPILER: clang
  #         CXX_COMPILER: clang++
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake ..
  #         make -j2
