name: windows
on: [push]
jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      #安装windows sdk
      # - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      #   with:
      #     sdk-version: 19041
      #设置mingw
      # - name: Set up MinGW
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x64
      - name: setup-bullet
        run: |
          mkdir build 
          cd build
          cmake .. -G "Visual Studio 16 2019" -D CMAKE_INSTALL_PREFIX=bullet-2.82-r2704 -D INSTALL_LIBS=ON -D USE_MSVC_RUNTIME_LIBRARY_DLL=On -D BUILD_CPU_DEMOS=Off -D BUILD_OPENGL3_DEMOS=Off -D BUILD_BULLET2_DEMOS=Off -D BUILD_UNIT_TESTS=Off
          cmake --build . --config Debug --target ALL_BUILD
          cmake --build . --config Debug --target INSTALL
          cmake --build . --config Release --target ALL_BUILD
          cmake --build . --config Release --target INSTALL
          ls 
      - name: build
      #-DCMAKE_SYSTEM_VERSION=10.0.19041.0
        run: |
          #mkdir build
          #cd build
          cmake .. -G "Visual Studio 16 2019"  -D SABA_BULLET_ROOT=bullet-2.82-r2704 -D SABA_GLFW_ROOT=glfw-3.3.6.bin.WIN64 
          ls
          msbuild xxx.sln
          #devenv [解决方案文件 | 项目文件 | 任意文件.扩展名] [开关]
