name: Example

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    #strategy:
     # matrix:
        #fail-fast: false
       # include:
        #  - { icon: '⬛', sys: mingw32 }
        #  - { icon: '🟦', sys: mingw64 }
        # - { icon: '🟨', sys: ucrt64  } # Experimental! 试验性的”。
        # - { icon: '🟧', sys: clang64 } # Experimental! 试验性的”。
    #name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      
    - name:  Setup MSYS2'
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-toolchain
        #pacboy: >-
        #  toolchain:p
        # cmake:p
        # ninja:p
    - name: '🚧 Build TOOL'
      run: |
        ls
        whereis cmake
        #cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        #cmake --build build